<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.DATA\ERP.DATA.csproj" />
    <ProjectReference Include="..\ERP.TRAN\ERP.TRAN.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\Inventario\Parametrizacion\" />
    <Folder Include="Components\Pages\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>..\..\..\.nuget\packages\microsoft.entityframeworkcore\10.0.11\lib\net10.0\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.IdentityModel.Tokens">
      <HintPath>..\..\..\.nuget\packages\microsoft.identitymodel.tokens\8.22.0\lib\net10.0\Microsoft.IdentityModel.Tokens.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Components\Pages\Inventario\Bodegas\BodegasDashboard.razor" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Components\Pages\Stores\Update.razor" />
  </ItemGroup>

</Project>
