<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CrossLayers\API\Inventario\Warehouse\Services\**" />
    <Compile Remove="CrossLayers\API\Inventario\Categoria\Services\**" />
    <Compile Remove="CrossLayers\API\Inventario\Movimientos\Services\**" />
    <EmbeddedResource Remove="CrossLayers\API\Inventario\Warehouse\Services\**" />
    <EmbeddedResource Remove="CrossLayers\API\Inventario\Categoria\Services\**" />
    <EmbeddedResource Remove="CrossLayers\API\Inventario\Movimientos\Services\**" />
    <None Remove="CrossLayers\API\Inventario\Warehouse\Services\**" />
    <None Remove="CrossLayers\API\Inventario\Categoria\Services\**" />
    <None Remove="CrossLayers\API\Inventario\Movimientos\Services\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CrossLayers\API\Inventario\Categoria\Enums\" />
    <Folder Include="CrossLayers\API\Inventario\Proveedor\Enums\" />
    <Folder Include="CrossLayers\API\Inventario\Proveedor\Services\" />
    <Folder Include="CrossLayers\API\Pos\Clients\Responses\" />
    <Folder Include="CrossLayers\API\Pos\Transactions\Responses\" />
    <Folder Include="CrossLayers\API\Stores\Responses\" />
    <Folder Include="CrossLayers\API\Stores\Requests\" />
    <Folder Include="CrossLayers\Core\Agreggates\Pos\Sales\" />
    <Folder Include="CrossLayers\Core\Agreggates\Pos\Transfers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.ApiEndpoints" Version="4.1.0" />
    <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
